name: buildndeploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: davidsiaw
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./docker/unit/Dockerfile
        push: true
        tags: davidsiaw/alesap-server:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: deploy
      uses: nvti/portainer-stack-deploy@de0d8b7e93e2cb12c1f335f463984a898de5105a
      with:
        portainer-host: ${{ secrets.PORTAINER_HOST }}
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        stack-name: ${{ secrets.PORTAINER_STACK }}
        stack-definition: 'stack-definition.yml'
        template-variables: '{"ALESAP_MASTER_KEY": "${{ secrets.ALESAP_MASTER_KEY }}"}'
        image: davidsiaw/alesap-server:latest
        prune-stack: true
        pull-image: true
